/**
 * All SDK error codes. Add new codes here, never inline.
 */
export const ErrorCodes = {
  // Network errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  SSE_DISCONNECT: 'SSE_DISCONNECT',

  // Auth errors
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',

  // Server errors
  SERVER_ERROR: 'SERVER_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // SDK errors
  NOT_INITIALIZED: 'NOT_INITIALIZED',
  INVALID_CONFIG: 'INVALID_CONFIG',
  FATAL_CRASH: 'FATAL_CRASH',

  // Media errors
  CAMERA_PERMISSION_DENIED: 'CAMERA_PERMISSION_DENIED',
  MICROPHONE_PERMISSION_DENIED: 'MICROPHONE_PERMISSION_DENIED',
  LOCATION_PERMISSION_DENIED: 'LOCATION_PERMISSION_DENIED',
  STT_UNAVAILABLE: 'STT_UNAVAILABLE',
  TTS_UNAVAILABLE: 'TTS_UNAVAILABLE',
  TTS_FAILED: 'TTS_FAILED',

  // Image errors
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',

  // Data loading errors
  HISTORY_LOAD_FAILED: 'HISTORY_LOAD_FAILED',
  LANGUAGES_LOAD_FAILED: 'LANGUAGES_LOAD_FAILED',

  // Session errors
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Onboarding errors
  ONBOARDING_FAILED: 'ONBOARDING_FAILED',

  // Generic
  UNKNOWN: 'UNKNOWN',
} as const;
