/**
 * Kotlin Code Generator
 *
 * Generates Kotlin data classes and sealed classes from TypeScript type definitions.
 * Reads JSDoc-annotated types from src/types/ and src/markdown/types.ts, then outputs
 * Kotlin files to the Android package output directories.
 *
 * Type mapping:
 *   TS interface        -> Kotlin data class
 *   TS union type       -> Kotlin sealed class
 *   TS string literal   -> Kotlin enum class
 *   TS optional (?)     -> Kotlin nullable (?)
 *   TS string           -> Kotlin String
 *   TS number           -> Kotlin Double (or Int/Long where annotated)
 *   TS boolean          -> Kotlin Boolean
 *   TS Array<T>         -> Kotlin List<T>
 *   TS Record<K,V>      -> Kotlin Map<K,V>
 *
 * Output files:
 *   - MarkdownNode.kt  (from src/markdown/types.ts)
 *   - Messages.kt      (from src/types/messages.ts)
 *   - Config.kt        (from src/types/config.ts)
 *   - Events.kt        (from src/types/events.ts)
 *   - Errors.kt        (from src/types/errors.ts)
 *
 * Usage:
 *   npx tsx codegen/kotlin-gen.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const PACKAGE_NAME = 'org.digitalgreenorg.farmerchat.sdk.types';

/** Source files to process and their corresponding output file names */
const SOURCE_MAP: Record<string, string> = {
  'src/markdown/types.ts': 'MarkdownNode.kt',
  'src/types/messages.ts': 'Messages.kt',
  'src/types/config.ts': 'Config.kt',
  'src/types/events.ts': 'Events.kt',
  'src/types/errors.ts': 'Errors.kt',
};

/** Default output directories for Android packages */
const OUTPUT_DIRS = [
  '../../packages/android-views/src/main/java/org/digitalgreenorg/farmerchat/sdk/types/generated',
  '../../packages/android-compose/src/main/java/org/digitalgreenorg/farmerchat/sdk/types/generated',
];

interface GenerateOptions {
  /** Root directory of packages/core (defaults to cwd resolution) */
  inputDir?: string;
  /** Override output directories (defaults to OUTPUT_DIRS) */
  outputDirs?: string[];
}

/**
 * Generate Kotlin data classes from TypeScript type definitions.
 *
 * TODO (Phase 3): Implement full AST-based codegen using ts-morph or the TS compiler API.
 * Current implementation writes documented placeholders that list what will be generated.
 */
export async function generateKotlin(options: GenerateOptions = {}): Promise<void> {
  const coreRoot = options.inputDir ?? path.resolve(__dirname, '..');
  const outputDirs = (options.outputDirs ?? OUTPUT_DIRS).map((d) =>
    path.resolve(coreRoot, 'codegen', d),
  );

  for (const outputDir of outputDirs) {
    fs.mkdirSync(outputDir, { recursive: true });

    for (const [sourceFile, outputFile] of Object.entries(SOURCE_MAP)) {
      const sourcePath = path.resolve(coreRoot, sourceFile);

      if (!fs.existsSync(sourcePath)) {
        console.warn(`  ⚠ Source not found, skipping: ${sourceFile}`);
        continue;
      }

      const content = generatePlaceholder(sourceFile, outputFile, sourcePath);
      const outputPath = path.join(outputDir, outputFile);
      fs.writeFileSync(outputPath, content, 'utf-8');
    }
  }
}

/**
 * Generate a documented placeholder Kotlin file.
 *
 * TODO: Replace with real AST parsing in Phase 3.
 * This reads the source TS file, extracts exported interface/type names,
 * and writes a Kotlin file with stub data classes listing what will be generated.
 */
function generatePlaceholder(sourceFile: string, outputFile: string, sourcePath: string): string {
  const source = fs.readFileSync(sourcePath, 'utf-8');

  // Extract exported interface and type names (simple regex, not full AST)
  const interfaces = [...source.matchAll(/export\s+interface\s+(\w+)/g)].map((m) => m[1]);
  const types = [...source.matchAll(/export\s+type\s+(\w+)/g)].map((m) => m[1]);

  const lines: string[] = [
    '// AUTO-GENERATED by codegen/kotlin-gen.ts',
    `// Source: ${sourceFile}`,
    `// Generated: ${new Date().toISOString()}`,
    '//',
    '// DO NOT EDIT — re-run `pnpm codegen` to regenerate.',
    '',
    `package ${PACKAGE_NAME}.generated`,
    '',
    '// TODO: Full codegen will be implemented in Phase 3.',
    '// The following types will be generated from the TypeScript source:',
    '',
  ];

  for (const name of interfaces) {
    lines.push(`// data class ${name}(...)`);
  }

  for (const name of types) {
    lines.push(`// sealed class ${name} { ... }`);
  }

  if (interfaces.length === 0 && types.length === 0) {
    lines.push('// (no exported types found)');
  }

  lines.push('');
  return lines.join('\n');
}

// Allow direct execution: npx tsx codegen/kotlin-gen.ts
if (require.main === module) {
  generateKotlin()
    .then(() => console.log('Kotlin codegen complete.'))
    .catch((err) => {
      console.error('Kotlin codegen failed:', err);
      process.exit(1);
    });
}
