/**
 * Swift Code Generator
 *
 * Generates Swift structs and enums from TypeScript type definitions.
 * Reads JSDoc-annotated types from src/types/ and src/markdown/types.ts, then outputs
 * Swift files to the iOS package output directories.
 *
 * Type mapping:
 *   TS interface        -> Swift struct (Codable, Equatable, Sendable)
 *   TS union type       -> Swift enum with associated values
 *   TS string literal   -> Swift enum: String, CaseIterable
 *   TS optional (?)     -> Swift optional (?)
 *   TS string           -> Swift String
 *   TS number           -> Swift Double (or Int where annotated)
 *   TS boolean          -> Swift Bool
 *   TS Array<T>         -> Swift [T]
 *   TS Record<K,V>      -> Swift [K: V]
 *
 * Output files:
 *   - MarkdownNode.swift  (from src/markdown/types.ts)
 *   - Messages.swift      (from src/types/messages.ts)
 *   - Config.swift        (from src/types/config.ts)
 *   - Events.swift        (from src/types/events.ts)
 *   - Errors.swift        (from src/types/errors.ts)
 *
 * Usage:
 *   npx tsx codegen/swift-gen.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

/** Source files to process and their corresponding output file names */
const SOURCE_MAP: Record<string, string> = {
  'src/markdown/types.ts': 'MarkdownNode.swift',
  'src/types/messages.ts': 'Messages.swift',
  'src/types/config.ts': 'Config.swift',
  'src/types/events.ts': 'Events.swift',
  'src/types/errors.ts': 'Errors.swift',
};

/** Default output directories for iOS packages */
const OUTPUT_DIRS = [
  '../../packages/ios-swiftui/Sources/FarmerChatSDK/Generated',
  '../../packages/ios-uikit/Sources/FarmerChatSDK/Generated',
];

interface GenerateOptions {
  /** Root directory of packages/core (defaults to cwd resolution) */
  inputDir?: string;
  /** Override output directories (defaults to OUTPUT_DIRS) */
  outputDirs?: string[];
}

/**
 * Generate Swift structs and enums from TypeScript type definitions.
 *
 * TODO (Phase 3): Implement full AST-based codegen using ts-morph or the TS compiler API.
 * Current implementation writes documented placeholders that list what will be generated.
 */
export async function generateSwift(options: GenerateOptions = {}): Promise<void> {
  const coreRoot = options.inputDir ?? path.resolve(__dirname, '..');
  const outputDirs = (options.outputDirs ?? OUTPUT_DIRS).map((d) =>
    path.resolve(coreRoot, 'codegen', d),
  );

  for (const outputDir of outputDirs) {
    fs.mkdirSync(outputDir, { recursive: true });

    for (const [sourceFile, outputFile] of Object.entries(SOURCE_MAP)) {
      const sourcePath = path.resolve(coreRoot, sourceFile);

      if (!fs.existsSync(sourcePath)) {
        console.warn(`  ⚠ Source not found, skipping: ${sourceFile}`);
        continue;
      }

      const content = generatePlaceholder(sourceFile, outputFile, sourcePath);
      const outputPath = path.join(outputDir, outputFile);
      fs.writeFileSync(outputPath, content, 'utf-8');
    }
  }
}

/**
 * Generate a documented placeholder Swift file.
 *
 * TODO: Replace with real AST parsing in Phase 3.
 * This reads the source TS file, extracts exported interface/type names,
 * and writes a Swift file with stub types listing what will be generated.
 */
function generatePlaceholder(sourceFile: string, outputFile: string, sourcePath: string): string {
  const source = fs.readFileSync(sourcePath, 'utf-8');

  // Extract exported interface and type names (simple regex, not full AST)
  const interfaces = [...source.matchAll(/export\s+interface\s+(\w+)/g)].map((m) => m[1]);
  const types = [...source.matchAll(/export\s+type\s+(\w+)/g)].map((m) => m[1]);

  const lines: string[] = [
    '// AUTO-GENERATED by codegen/swift-gen.ts',
    `// Source: ${sourceFile}`,
    `// Generated: ${new Date().toISOString()}`,
    '//',
    '// DO NOT EDIT — re-run `pnpm codegen` to regenerate.',
    '',
    'import Foundation',
    '',
    '// TODO: Full codegen will be implemented in Phase 3.',
    '// The following types will be generated from the TypeScript source:',
    '',
  ];

  for (const name of interfaces) {
    lines.push(`// struct ${name}: Codable, Equatable, Sendable { ... }`);
  }

  for (const name of types) {
    lines.push(`// enum ${name} { ... }`);
  }

  if (interfaces.length === 0 && types.length === 0) {
    lines.push('// (no exported types found)');
  }

  lines.push('');
  return lines.join('\n');
}

// Allow direct execution: npx tsx codegen/swift-gen.ts
if (require.main === module) {
  generateSwift()
    .then(() => console.log('Swift codegen complete.'))
    .catch((err) => {
      console.error('Swift codegen failed:', err);
      process.exit(1);
    });
}
